spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  thymeleaf:
    enabled: true

envio:
  email:
    remetente: ${MAIL_USERNAME}
    nomeRemetente: ${MAIL_NOME_REMETENTE}

server:
  port: ${SERVER_PORT:8082}